### ISSUE TITLE
access to metadata file T1D_neutrophils_metadata_GEO.xlsx

### ISSUE THREAD

**Issue by gsiegwald** [mjdufort/Battaglia_T1D_neutrophils#1]
Dear Mr Dufort,

I'm curently trying to analyse the GSE110914 GEO dataset thanks to your scripts.
At the beginning of "T1D_neutrophils_2_differential_expression_analysis.R" you read an annotation file "T1D_neutrophils_metadata_GEO.xlsx". 
Unfortunately I haven't been able to find this file on the corresponding GEO webpage (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE110914).
Could you inform me if this file is publicly available, and if so where can it be downloaded.

Thank you in advance for your help,

Guillaume

**Comment by mjdufort** [comment]
Dear Guillaume,

My apologies.  That referred to the metadata file that was included with the GEO submission.  While the data are all present on GEO, they are not in the same format.  As soon as I have time, I will update the code to pull the sample metadata directly from the GEO repository using GEOquery::getGEO(), and match the variable names to their usage downstream.

Matt

**Comment by gsiegwald** [comment]
Dear Matt,
Thank you very much for your response and for updating your code.
It is really helpful that you've put the code of the analysis online, I wish more people would do the same!
Best,
Guillaume

**Comment by mjdufort** [comment]
I finally had a chance to update the code.  It now pulls both the annotation and counts data from GEO using GEOquery.  It's working for me now, but if you run into any additional issues, please let me know!

Matt
